FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o client ./cmd/client

FROM scratch

COPY --from=builder /app/client /client

ENV WOW_SERVER_ADDR=server:4000

ENTRYPOINT ["/client"]